node:
  home: ${gravitee.home}

plugins:
  registry:
    path: ${gravitee.home}/plugins

repository:
  type: mongodb
  mongodb:
    dbname: gravitee
    host: localhost
    port: 27017

security:
  type: basic-auth