
management:
  type: mongodb
  mongodb:
    dbname: gravitee
    host: localhost
    port: 27017

security:
  type: basic
  providers:
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER
        - user:
          username: admin
          password: admin
          roles: ADMIN
    - type: gravitee
      password-encoding: true

email:
  host: smtp.my.domain
  # port: 465
  from: noreply@my.domain
  username: user@my.domain
  password: password

templates:
  path: ${gravitee.home}/templates